from config import ALL_LINE, PROGRAM_AUTHENTICATION_CLYTH, CURRENT_LOCALIZATION
years_copyleft = "2024 - 2026"

# Локализации
localizations = {
    "ct": {
        "": "",
    },
    "ru": {
        "RLP": "Защита Нагрузки",
        "ARM": "Мастер Автозагрузки",
        "B": "Браузер",
        "CASH": "Обработчик скриптов",
        "PM": "Менеджер Процессов",
        "FM": "Файловый Менеджер",
        "UA": "Разблокировка всего",
        "FE": "Редактор Файлов",
        "FR": "Замена редко используемых файлов",
        "CM": "Главное меню",
        "SP": "Пугало от вирусов",
        "CC": "Очистка Кэша",
        "Console": "Консоль разработчика",
        "UM": "Менеджер Пользователей",
        "R": "Перезапуск ПК",
        "Run": "Запуск всего",
        "OBPC": "Голосовое Управление",
        "encryption": "Шифрование",
        "EC": "Изменение Критичности процесса",
        "GFA": "Получение полных прав",
        "OF": "Прочие Компоненты",
        "RS": "Генератор Заголовков",
        "E": "Выход из программы",
        "AP": "О Программе",
        "SAU": "Настройки",
        "RM": "Мониторинг Реестра",
        "SIM": "Менеджер Установки",
        # AP
        "version_component": "Версии Компонентов",
        "pac": "Ключ КПП",
        "general_component": "Главные Компоненты",
        "program_kernel": "Ядро программы (трей)",
        "mini_component": "Мини Компоненты",
        "system_component": "Системные Компоненты",
        "donation_steam_text": "Поддержать через трейд в Steam",
        "license": "Лицензия",
        "website_neo_organization": "Веб-Сайт NEO Organization",
        "about_program_text": f"Антивирус Монтировка!\nВытащит любой гвоздь из крышки гроба вашего ПК!\n(как минимум попытается, а если не смог - поставь Linux)\nCreated by NEO Organization\nPowered by Departament K\nCoded by @AnonimNEO, Всего строчек кода : {ALL_LINE}\nПрограммисты/Задумщики/Художники/Тестировщики : @AnonimNEO\nЛицензия: GPL v3.0 Copyleft 🄯 {years_copyleft}\n",
        "ap_exception_text": "В Компоненте AboutProgram произошла неизвестная ошибка!",
        "not_stable": "не доступен из-за нестабильности",
        "read_dir_error": "Ошибка при чтении каталога",
        "read_image_error": "Не удалось загрузить изображение",
        # T
        "import_error": "Ошибка импорта",
        "replacement_is_used": "Используется замена",
        "component_import_error": "Ошибка импорта Компонента",
        "component": "Компонент",
        "not_available": "не доступен",
        "not_available2": "не доступна",
        "library": "Библиотека",
        "critical_fail_detect": "Обнаружены критические повреждения программы! Ядро программы не может быть запущено",
        "damage": "Повреждения",
        "RUN_IN_RECOVERY": "Запуск в среде восстановления Шindows",
        "run_in_normal": "Запуск в стандартной среде Шindows",
        "environment_error": "Ошибка при определении среды",
        "load_bush": "Загрузка кустов реестра с диска",
        "unload_bush": "Завершение работы, выгрузка кустов реестра...",
        "runtime_error": "Критическая ошибка при инициализации программы",
        "use_default_font": "Используется шрифт по умолчанию",
        "trey_error": "Ошибка трея",
        "open_with": "Открыть с помощью",
        "bad_password_for_console": "Неправильный ввод капчи.\nКонсоль разработчика не будет запущена.",
        "enter_number": "Введите число",
        "open": "Открыть",
        "utilities": "Утилиты",
        "icon_start_error": "Ошибка запуска иконки",
        "t_critical_error": "В Компоненте Trey произошла неизвестная ошибка",
        "multiprocessing_error": "Критическая ошибка при многопоточности",
        "restart_program": "Перезапустить программу",
        "admin_error": "Ошибка при получении прав администратора",
        "checking_damage_error": "ошибка при проверке критических повреждений",
        "emergency_restart": "Аварийный перезапуск",
        "attempt_import_t": "Попытка запуска программы как отдельного модуля!",
        "start_cash_error": "Ошибка запуска движка скриптов",
        "enable_debug_mode": "Включить Тестовый режим",
        "warning_debug_mode_on": "ВНИМАНИЕ\nВключен тестовый режим!",
        "documentation": "Документация",
        "fatal_error": "Фатальная ошибка",
        "in_start_crowbar": "при запуске Антивируса Монтировка, запуск не возможен. Отсутствует графическая библиотека tkinter, подробнее в логах.",
        # ARM
        "scheduler_error": "Не удалось подключиться к планировщику задач",
        "edit_task_error": "Ошибка изменения состояния задачи",
        "delete_task_error": "Ошибка удаления задачи",
        "user_not_found": "Не найден пользователь",
        "enter_user_name": "Введите нужное имя пользователя",
        "metadata_error": "Ошибка при получении метаданных файла",
        "startup_error": "Ошибка при доступе к папке автозагрузки пользователя",
        "key_not_found": "Ключ реестра не найден",
        "read_key_error": "Ошибка при считывании ключа реестра",
        "create_key": "Создан параметр реестра",
        "with_type": "с типом",
        "in": "в",
        "permission_error": "Недостаточно прав",
        "create_key_error": "Ошибка при создании параметра реестра",
        "update_key": "Успешно изменён параметр реестра",
        "update_key_error": "Ошибка при изменении параметра реестра",
        "delete_key": "Удален параметр реестра",
        "delete_key_error": "Удален параметр реестра",
        "file_delete": "Удалён файл",
        "file_delete_error": "Ошибка при удалении файла",
        "save_xml_task_error": "Ошибка сохранения XML задачи",
        "task_error": "Ошибка обработки задачи",
        "task_dir_error": "Каталог задач не найден",
        "xml_task_error": "Ошибка обработки файла задачи",
        "on": "включена",
        "off": "отключена",
        "task": "Задача",
        "success": "успешно",
        "from_com": "через COM",
        "from_xml": "через XML",
        "xml_error": "Ошибка XML",
        "delete_task_com": "удалена через COM",
        "xml_task_delete": "XML файл задачи удален",
        "xml_task_delete_error": "Ошибка удаления XML файла",
        "delete_file?": "Вы уверены, что хотите удалить параметр реестра",
        "enter_new_name_key": "Введите имя нового параметра реестра",
        "for": "для",
        "arm_help_text": 'Во вкладке планировщик отображается так много задач, потому что вирусы могли модернизировать задачи, но такое крайне редко, поэтому вы можете отключить отображение задач без графа "создан". Для этого нажмите на пункт в верхней панели окна: вид->Показывать только задачи с датой.',
        "arm_critical_error": f"В Компоненте AutoRunMaster произошла неизвестная ошибка!",
        "danger": "Угроза",
        "suspend_process_for_name": "Заморозить процессы с именем",
        "kill_process_for_name": "Убить процессы с именем",
        "action_error": "ошибка при действии",
        # B
        "browser_called": "браузер вызван с параметрами",
        "browser_run_in_recovery": "В среде восстановления не поддерживается загрузка страниц из интернета.\nОднако просмотр офлайн страниц доступен",
        "download_start": "Начато скачивание",
        "download_cancel": "Отменено скачивание",
        "download_completed": "Скачивание завершено",
        "file_download_on": "Файл успешно загружен в",
        "download_fail": "Ошибка при скачивании",
        "enter_url_or_file_path": "Введите URL или путь к файлу",
        "new_tab": "Новая вкладка",
        "html_loaded": "Загружен HTML контент",
        "file_loaded": "Загружен файл",
        "page_loaded": "Загружена страница",
        # CASH
        "script_deleted": "Скрипт удалён",
        "script_deleted_error": "Ошибка при удалении скрипта",
        "execution_completed": "Выполнение завершено",
        "exec_script_error": "Ошибка при выполнении скрипта",
        "script_config": "Конфигурация скрипта",
        "file_transferred": "Передан файл",
        "command_not_found_for_file": "Антивирус Монтировка не имеет команд для данного типа файла",
        # Console
        "crowbar_console": "Консоль Разработчика Антивируса Монтировка",
        "crowbar_console_text": "В данной консоли вы оперируете копиями переменных так, что ваши действия вряд ли могут повредить программу.\nЕсли это произошло перезапустите консоль или программу.\n",
        "attempt_command": "попытка выполнить команду",
        "exit_with_console_text": "Не не Я не дам тебе обойти капчу (как минимум попытаюсь)",
        # EC
        "open_process_error": "Не удалось открыть процесс",
        "error_code": "Код ошибки",
        "installed": "установлена",
        "removed": "снята",
        "process_critical": "Критичность процесса",
        "target": "целевое",
        "edit_critical_error": "Ошибка при изменения критичности",
        "edit_critical_unknown_error": "Неизвестная ошибка при изменении критичности",
        "process": "Процесс",
        "not_found": "не найден",
        "criticality_status": "Значение критичности процесса",
        "changed_to": "изменено на",
        "no_changed": "не было изменено",
        "ec_critical_error": "В Компоненте EditCriticality произошла неизвестная ошибка",
        # OF
        "pac_text": f"Ключ Подлинности Программы (КПП) - это ключ для подтверждения, что эта программа подлинная.\nЕсли вы видите ключ который вы указывали при компиляции, значит перед вами настоящий Антивирус Монтировка.\nЕсли ключ не совпадает с вашим - значит перед вами клон программы который маскируется под Антивирус Монтировка.\n\nКПП - {PROGRAM_AUTHENTICATION_CLYTH}",
        "start_thread": "Успешно запущен поток для",
        "start_process": "Успешно запущен процесс для",
        "start_theard_error": "Ошибка при запуске потока для процесса",
        "start_process_error": "Ошибка при запуске процесса для процесса",
        "restart_ca": "Перезапуск программы",
        "system_found": "Система найдена на",
        "unknown_error": "Неизвестная ошибка",
        "bush_not_found": "Файл куста не найден",
        "bush": "Куст",
        "success_load": "успешно загружен из",
        "load_bush_error": "Ошибка при загрузке куста",
        "success_unload": "успешно выгружен",
        "unload_bush_error": "Ошибка при выгрузке куста",
        "get_user_name_error": "Ошибка получения имени пользователя",
        "open_file_error": "Не удалось открыть файл",
        "with_program": "с помощью указанной программы",
        "start_error": "Ошибка при запуске",
        "start_command_error": "Ошибка при выполнении команды",
        "execute": "Выполнить",
        "enable_debug_mode_text": "Вы уверены, что хотите включить Тестовый режим?\nЭто приведёт к более точным логам с возможно чувствительными данными.\nТакже в тестовом режиме будут разблокированы тестовые Компоненты.",
        "debug_mode_on": "Включен ТЕСТОВЫЙ РЕЖИМ",
        "decoy_mode_error": "Ошибка при создании фейковой активности",
        "reg_key_delete_error": "Ошибка при удалении ключа реестра",
        "reg_key_delete": "Удалён ключ реестра",
        "create_reg_key": "Создан ключ реестра",
        "protect_window_on": "Защита от перемещения окна включена",
        "protect_window_off": "Защита от перемещения окна отключена",
        "window_block": "Окно заблокировано на",
        "second": "сек",
        "excessive_movements": "Слишком частые движения",
        "for2": "за",
        "milliseconds": "мс",
        "sharp_jump": "Резкий скачок",
        "attack": "Атака",
        "start_in_ghost_mode": "Запущено в скрытом режиме",
        "start_in_ghost_mode_error": "Ошибка при запуске в cкрытом режиме",
        "browser_problem": "Встроенный браузер имеет проблемы и на данный момент отсутствует в программе.\nОткрыть ссылку на документацию в браузере по умолчанию?",
        # E
        "dyrachok_test_log_text": "Проверка на дурочка не прошла",
        "dyrachok_test_text": "Вы смотрите тикток!\nПрограмма не будет закрыта.",
        "watch_tiktok?": "Смотрите ли вы тикток?",
        "exit_error": "Ошибка при выходе",
        "exit_program": "Завершение работы программы...",
        "bad_capcha": "Неправильный ввод капчи.\nПрограмма не будет закрыта.",
        "enter_result_example": "Введите результат данного примера",
        "bad_result_example": "ввод примера не верен",
        "bad_enter_number": "Неправильный ввод числа",
        "want_exit?": "Вы действительно хотите выйти из данного программного обеспечения?",
        "attempting_to_exit": "Попытка выхода из программы",
        "cancel_exit": "Отмена выхода",
        "e_critical_error": "В Компоненте Exit произошла неизвестная ошибка!",
        # GFA
        "not_dir": "Путь не существует",
        "full_access_set": "Полные права установлены",
        "error": "Ошибка",
        "file_error": "Ошибка при работе с файлом",
        "to_access": "для доступа к",
        "get_sid_error": "Ошибка получения SID пользователя",
        "get_description_error": "Ошибка получения дескриптора безопасности",
        "ace_error": "Ошибка добавления ACE",
        "set_access_error": "Ошибка установки прав",
        "success_set_full_access": "Полные права на реестр установлены",
        "regedit_error": "Ошибка при работе с реестром",
        # R
        "attempt_to_reboot": "Попытка перезагрузки через",
        "r_critical_error": "В Компоненте Restart произошла неизвестная ошибка в методе",
        "next_method": "Переход к следующему способу",
        "all_method_used": "Были выполнены все возможные способы перезагрузки шindows, не один не увенчался успехом.",
        # SP
        "simulation": "Симуляция",
        "removal": "Удаление",
        "create_dir": "Создан каталог",
        "create_dir_error": "Ошибка при создании каталога",
        "create_file": "Создан файл",
        "create_file_error": "Ошибка при создании файла",
        "delete_dir": "Удалён каталог",
        "delete_dir_error": "Ошибка при удалении каталога",
        "start_simulation": "Запуск симуляции для",
        "simulation_for": "Симуляция для",
        "completed": "завершена",
        "simulation_completed": "Симуляция завершена.",
        "sp_confirmation": "Вы уверены, что хотите удалить все фантомные элементы?\nЭто может повредить настоящие установленные.",
        "delete_simulation": "Удаление симуляции для",
        "delete_simulation_for": "Удаление симуляции для",
        "delete_completed": "Удаление завершено.",
        "sp_critical_error": f"В Компоненте ScarecrowProtection произошла неизвестная ошибка!",
        # UA
        "start_recovery_font": "Начало восстановления шрифтов",
        "font_dir_not_found": "Каталог шрифтов не найден",
        "font": "Шрифт",
        "restored": "восстановлен",
        "correct_font": "уже корректно записан в реестре",
        "add_in_registry": "добавлен в реестр",
        "font_error": "Ошибка при обработке шрифта",
        "delete_orphan_font": "Удалён параметр сиротского шрифта",
        "delete_orphan_font_error": "Ошибка при удалении параметра-сирот",
        "recovery_font_complete": "Восстановление шрифтов завершено. Найдено",
        "removed_orphans": "удалено сирот",
        "recovery_font_error": "Ошибка при восстановлении шрифтов",
        "parameter": "Параметр",
        "successfully_reset_to": "успешно сброшен в",
        "unsupported_type_for": "Неподдерживаемый тип для",
        "not_found_pass": "не найден, пропуск",
        "reset_error": "Ошибка при сбросе",
        "block_detect": "Обнаружены блокировки в",
        "delete_block": "Удалены блокировки",
        "component_work_complete": "Работа компонента завершена",
        "ua_critical_error": "В Компоненте UnlockAll произошла неизвестная ошибка:",
        "au_result": "Компонент разблокировка всего завершил работу результаты",
        "unlock": "Разблокировано ✅",
        "unlock_error": "Ошибка разблокировки❌",
        "blocks": "Блокировки",
        "mouse": "мыши",
        "explorer": "проводника",
        "user": "пользователя",
        "systems": "системы",
        "fonts": "шрифтов",
        "check_fonts": "Проверка целостности шрифтов",
        "all_fonts=": "Все параметры шрифтов имеют одинаковое значение",
        "not_ttf_or_otf": "В значениях параметров отсутствуют .ttf или .otf файлы",
        "font_problem_detect": "Обнаружены проблемы с шрифтами, запуск восстановления",
        "restore_fonts_check_success": "Проверка целостности шрифтов завершена успешно, восстановление не требуется",
        "check_fonts_error": "Неизвестная ошибка при проверке шрифтов",
        "legal_notice": "Сообщение перед входом в систему",
        # UM
        "net_error": "Команда net завершилась с ошибкой",
        "system_command_error": "Системная ошибка при выполнении команды",
        "user_name": "Имя пользователя",
        "create_user": "Создать пользователя",
        "delete_users": "Удалить выбранных",
        "change_password": "Изменить пароль",
        "get_user_list_error": "Ошибка при загрузке списка пользователей",
        "password": "Пароль",
        "enter_all_data": "Заполните все поля.",
        "success_create": "успешно создан",
        "create_user_error": "Ошибка при создании пользователя",
        "select_user": "Выберите пользователя.",
        "cant_delete_self": "Нельзя удалить себя",
        "what_did_you": "Иш, что захотел",
        "deleted": "удален",
        "delete_user_error": "Ошибка при удалении пользователя",
        "enter_new_password": "Введите новый пароль:",
        "not_empty": "не может быть пустым.",
        "reset": "Сбросить",
        "reset2": "сброшен",
        "password_for_user": "Пароль для пользователя",
        "change_password_error": "Ошибка при сбросе пароля для",
        "um_critical_error": "В Компоненте UsersManager произошла неизвестная ошибка!",
        # CC
        "start_clean": "Запуск Очистки",
        "from": "из",
        "delete_files_error": "Ошибка при удалении следующих файлов",
        "delete_files_success": "Успешно удалённые файлы",
        "cc_log_dir": "Лог файл был создан по пути",
        "cc_critical_error": "В Компоненте ClearCache произошла неизвестная ошибка!",
        # CM
        "components": "Компоненты",
        "protect": "Защита",
        "control": "Управление",
        "cm_critical_error": "В Компоненте CrowbarMenu произошла неизвестная ошибка!",
        # Theme
        "dark": "Тёмная",
        "white": "Светлая",
        "red": "Красная",
        "blue": "Синяя",
        "green": "Зелёная",
        "contrast": "Контрастная",
        "gray": "Серая",
        "orange": "Оранжевая",
        "themes": "Темы",
        "topmost": "Поверх всех окон",
        "on2": "вкл",
        "off2": "выкл",
        "help": "Помощь",
        "view": "Вид",
        "show_date": "Показывать только задачи с датой",
        # FE
        "file": "Файл",
        "save": "Сохранить",
        "save_as": "Сохранить как",
        "exit": "Выход",
        "editing": "Редактирование",
        "cancel": "Отменить",
        "repeat": "Повторить",
        "cut": "Вырезать",
        "copy": "Копировать",
        "paste": "Вставить",
        "select_all": "Выделить всё",
        "font_size": "Размер шрифта",
        "new_file": "Новый файл",
        "text_file": "Текстовые файлы",
        "all_files": "Все файлы",
        "file_not_found": "Файл не найден",
        "success_saved": "успешно сохранён",
        "save_changes?": "У вас есть несохранённые изменения. Сохранить файл перед выходом?",
        "match_case": "Учитывать регистр",
        "whole_words": "Слова Целиком",
        "back": "Назад",
        "next": "Далее",
        "fe_critical_error": "В Компоненте FileEditor произошла неизвестная ошибка!",
        "cuttlefish": "Сепия",
        "crowbar_scripts": "Скрипты Антивируса Монтировка",
        "load_file": "при загрузке файла",
        "save_file": "при сохранении файла",
        # FR
        "created": "Создан",
        "replaced": "заменено",
        "on_disc": "на диске",
        "replace_file_not_found": "Не удалось заменить файл",
        "select_file": "Сначала выберите или укажите путь к файлу!",
        "backup": "Бэкап",
        "on_dir": "по пути",
        "restore": "Восстановить",
        "from_backup": "из бэкапа",
        "restore_from_backup": "Восстановлено из бэкапа",
        "when_restoring_a_file": "при восстановлении файла",
        "your_way": "Свой путь",
        "sticky_keys": "Залипание клавиш",
        "specialist_possibilities": "Спец. возможности",
        "task_manager": "Диспетчер задач",
        "explorer": "Проводник",
        "what_to_replace": "На, что заменить",
        "review": "Обзор",
        "what_are_replace": "Что заменяем",
        "select_preset": "Выберите пресет...",
        "replace": "Заменить",
        # FM
        "skip_file": "Пропущен файл",
        "copy_path": "Скопировать путь",
        "search": "Поиск",
        "loading": "Загрузка",
        "enter_path": "Введите путь",
        "available_disks": "Доступные диски",
        "path": "Путь",
        "delete": "Удалить",
        "elements": "элементов",
        "you_want_to_delete": "Вы уверены, что хотите удалить",
        "delete_error": "Ошибка при удалении",
        "elements_copy": "Скопировано элементов",
        "clipboard_is_empty": "Буфер обмена пуст",
        "paste_error": "Ошибка вставки",
        "access_check_error_for": "Ошибка проверки доступа для",
        "properties": "Свойства",
        "meaning": "Значение",
        "name": "Имя",
        "location": "Расположение",
        "size": "Размер",
        "changed": "Изменён",
        "opened": "Открыт",
        "file_version": "Версия файла",
        "author": "Автор",
        "access_for": "Права доступа (для",
        "full_access": "Полный доступ",
        "reading": "Чтение",
        "record": "Запись",
        "launch": "Запуск",
        "collecting_properties_error": "Ошибка при сборе свойств для",
        "read_file_properties_error": "Не удалось прочитать свойства файла",
        "invalid_characters": "содержит недопустимые символы",
        "current": "Текущий",
        "dir": "Каталог",
        "new_name_for": "Новое имя для",
        "already_exists": "уже существует",
        "name_file_or_dir": "Файл или каталог с именем",
        "renamed": "Переименовано",
        "when_renaming": "при переименовании",
        "enter_data_file": "Введите содержимое для файла",
        "restore_focus_error": "Не удалось восстановить фокус на",
        "up": "Вверх",
        "rename": "Переименовать",
        "get_full_access": "Получить полные права",
        "edit_file": "Отредактировать файл",
        "create": "Создать",
        "update": "Обновить",
        "not_dir_selected": "Не выбран каталог для вставки",
        "source_file_not_found": "Источник не найден (возможно, был перемещен)",
        "dont_copy_in_in": "Нельзя скопировать или переместить элемент в тот же каталог",
        "replace_it": "Заменить его?",
        "copied2": "Скопирован",
        "fm_help_text": "Добро пожаловать в Файловый Менеджер!\nДанный Компонент поддерживает:\n1)Полное управление с клавиатуры\n2)Поиск - чтобы его вызвать нажмите на пункт в верхней левой части окна.",
        "text_for_search": "Текст для поиска:",
        "in_current_dir": "В текущем каталоге",
        "cancel2": "Отмена",
        "enter_text_for_search": "Введите текст для поиска:",
        "not_current_tab_for_search": "Нет активной вкладки для поиска.",
        "files_containing": "Файлы, содержащие",
        "not_founded": "не найдены",
        "info_dir_error": "Ошибка получения информации о каталоге",
        "info_file_error": "Ошибка получения информации о файле",
        "search_result": "Результаты поиска",
        "fm_exit": "Вы уверены, что хотите выйти?",
        "fm_critical_error": "В FileManager произошла неизвестная ошибка!",
        "fm_search_text": "Поиск начался, результаты начнут подгружаться в таблицу уже сейчас, однако функции сортировки сейчас не будут работать.\nКогда поиск завершится вся таблица будет отсортирована автоматически.\nТакже вы можете продолжить работу в другой вкладке.",
        "search_error": "Ошибка во время поиска",
        "search_completed": "Поиск завершён",
        "read_file_error": "Ошибка при чтении файла",
        # PM
        "info_process_error": "Ошибка при получении информации о процессе",
        "ok": "ОК",
        "at": "при",
        "kill_processes": "Убить процессы",
        "suspend": "Заморозить",
        "resume": "Разморозить",
        "make_it_critical": "Сделать критичными",
        "remove_criticality": "Снять критичность",
        "to_file": "к файлу",
        "pm_help_text": "Добро пожаловать в Менеджер Процессов, он поддерживает:\n1)Выделение нескольких процессов и работу с ними\n2)Поиск - чтобы его вызвать нажмите на пункт вверху левой части окна.\n3)Замороженные процессы - помечены серым цветом, а критические - красным. Также есть вкладки для удобной навигации.\n\nУчтите, что windows создаёт свои 4 критических процессов svhost.exe, но вирус может изменить эти значения, будьте бдительны!",
        "cancel_search": "Прекратить поиск",
        "actions": "Действия",
        "pm_critical_error": "В Компоненте ProcessManager произошла неизвестная ошибка!",
        "kill_delete_file_process": "Убить + удалить файл процесса",
        "process_dont_close": "не закрылся за 3 секунды",
        # Run
        "standard": "Стандартные",
        "regedit": "редактор реестра",
        "taskmgr": "диспетчер задач",
        "notepad": "блокнот",
        "explorer": "проводник",
        "cmd": "командная строка",
        "powershell": "PowerShell",
        "commands": "Команды",
        "cancel_reboot": "Отменить перезагрузку/выключение",
        "reboot_pc": "Перезагрузить ПК",
        "shutdown_pc": "Выключить ПК",
        "end_session": "завершить сеанс",
        "mode": "Режим:",
        "professional": "профессиональный",
        "simplified": "упрощённый",
        "file2": "файла",
        # SAU
        "compilations": "Компиляции",
        "command_end_with_code": "Команда завершилась с кодом",
        "t_compilation_is_finish": "Компиляция Компонента Trey завершена!",
        "setting_saved_in": "Настройки успешно сохранены в",
        "settings_save_error": "Ошибка при сохранении настроек",
        "settings_backup_created_ob_path": "Резервная копия настроек создана по пути",
        "settings_export_success": "Экспорт прошёл успешно, сохранено в",
        "settings_backup_created_error": "Ошибка при создании резервной копии",
        "settings_export_error": "Ошибка при экспорте настроек",
        "archive": "Архив",
        "not_compilation": "Перекомпиляция не возможна",
        "bad_archive": "Неверный формат архива или поврежденный архив",
        "success_unpacked": "успешно распакован",
        "unpacked_archive_error": "Ошибка при распаковке архива",
        "moved": "перемещено",
        "content": "Содержимое",
        "moved_error": "Ошибка при перемещении файлов",
        "enter_path_to_image": "Введите каталог куда переместить изображения\nНичего не вводите если изображения уже в нужном каталоге\n(например вы просто обновляете программу)",
        "for_copy_image": "изображений в каталог",
        "for_copy": "для копирования",
        "copy_error": "Ошибка при копировании",
        "copy_file_error": "изображений\nВозможно вы ввели неправильные данные, вы можете сами переместить файлы они находятся в каталоге с программой.",
        "enter_exe_name": "Введите каталог куда переместить исполняемый файл\nвместе с именем файла, обязательно с расширением .exe!",
        "copy_exe_error": "Возможно вы ввели неправильные данные, вы можете сами переместить файлы они находятся в каталоге с программой",
        "create_lnk_success": "Ярлык успешно создан на рабочем столе",
        "create_lnk_error": "Ошибки при создании ярлыка",
        "successfully_changed_to": "успешно изменено на",
        "add_to_autorun_error": "Ошибка при добавлении программы в автозагрузку",
        "add_program_to_autorun": "Добавить программу в автозагрузку?",
        "add_program_to_autorun_error": "Произошла ошибка во время добавления программы в автозагрузку",
        "path_must_string": "Путь должен быть строкой",
        "number_must_be_1_to": "Число должно быть от 1 до",
        "enter_number": "Введите число.",
        "enter_string": "Значение должно быть строкой",
        "field_cannot_be_empty": "Поле не может быть пустым.",
        "use": "Используйте",
        "must_list": "Должен быть список, кортеж, множество или словарь",
        "syntaxis_error": "Ошибка синтаксиса",
        "invalid_format": "Некорректный формат",
        "must_be_dictionary": "Значение должно быть словарем",
        "dictionary_must_contain_key": "Словарь должен содержать ключ",
        "read_comments_error": "Ошибка при чтении комментариев из",
        "parsing_error": "Ошибка парсинга",
        "fix_problem_in_fields": "Исправьте ошибки в полях (отмечены красным)",
        "recompilation_required_continue": "Требуется перекомпиляция!\nПродолжить?",
        "create_backup": "Создание резервной копии...",
        "create_backup_error": "Ошибка при создании бэкапа",
        "save_settings": "Сохранение настроек...",
        "save_settings_error": "Ошибка при сохранение настроек",
        "unpacking_source_code": "Распаковка исходников...",
        "unpacking_source_code_error": "Ошибка при распаковка исходников",
        "preparing_files": "Подготовка файлов...",
        "preparing_files": "Подготовка файлов...",
        "compilation": "Компиляция",
        "during_recompilation": "при перекомпиляции",
        "copying_files": "Копирование файлов...",
        "adding_to_autorun": "Добавление в автозагрузку...",
        "completed": "завершено",
        "delete_compiling_cache": "Вы уверены, что хотите удалить весь кэш и временные .py файлы?",
        "clean_completed_deleted_objects": "Очистка завершена.\nУдалено объектов",
        "clean_cache_error": "Ошибка при очистке кэша",
        "ready": "Готов к работе",
        "open_error": "Не удалось открыть",
        "log": "лог файла",
        "export": "Экспорт",
        "import": "Импорт",
        "delete_cache": "Удалить Кэш",
        "apply": "Применить",
        "sau_start_text": "Учтите, что изменение параметров невозможно без перекомпиляции программы!\n\nРекомендуем сделать экспорт настроек (тем самым сделать резервную копию настроек), перед изменениями\n\nВы хотите продолжить?",
        "icon_not_found": "Не найдена иконка программы, если хотите указать собственную Нажмите ОК и в появившемся окне выберите иконку, если нет то нажмите ОК и в открывшемся окне выберите Отмена",
        "enter_program_name": "Введите желаемое название исполняемого файла,\nБЕЗ расширения файла!",
        "enter_log_name": "Введите название лог файла для установщика\nМожете ввести полный путь для данного лог файла\nили ничего не вводить если хотите отключить логирование",
        "sau_critical_error": f"Во время установки произошла неизвестная ошибка",
        # GUI
        "custom": "Пользовательская",
        "parameter": "параметра",
        "type": "Тип",
        "date": "Дата",
        "creation": "создания",
        "changes": "Изменения",
        "discoveries": "Открытия",
        "system": "Системная",
        "bit": "Битность",
        "registry": "Реестр",
        "scheduler": "Планировщик",
        "state": "Состояние",
        "unknown": "неизвестно",
        "no": "Нет",
        "change": "Изменить",
        "turn_off": "Отключить",
        "turn_on": "Включить",
        "no_data": "Н/Д",
        "yes": "Да",
        "all_process": "Все Процессы",
        "process2": "Процесса",
        "critical": "Критичность",
        "status": "Статус",
        "user2": "Пользователь",
        "frozen": "Заморожен",
        "critical_process": "Критичные Процессы",
        "suspend_process": "Замороженные Процессы",
        "things": "шт",
        "admin": "Администратор",
        "started": "Запущен",
        "guest": "Гость",
    },
    "en": {
        "RLP": "Load Protection",
        "ARM": "Startup Wizard",
        "B": "Browser",
        "CASH": "Script Handler",
        "PM": "Process Manager",
        "FM": "File Manager",
        "UA": "Unlock All",
        "FE": "File Editor",
        "FR": "Replace Rarely Used Files",
        "CM": "Main Menu",
        "SP": "Virus Scarecrow",
        "CC": "Cache Cleaner",
        "Console": "Developer Console",
        "UM": "User Manager",
        "R": "Restart PC",
        "Run": "Run All",
        "OBPC": "Voice Control",
        "encryption": "Encryption",
        "EC": "Change Process Criticality",
        "GFA": "Get Full Rights",
        "OF": "Other Components",
        "RS": "Header Generator",
        "E": "Exit the program",
        "AP": "About the Program",
        "SAU": "Settings",
        "RM": "Registry Monitoring",
        "SIM": "Installation Manager",
        # AP
        "version_component": "Component Versions",
        "pac": "Gearbox Key",
        "general_component": "Main Components",
        "program_kernel": "Program Kernel (tray)",
        "mini_component": "Mini Components",
        "system_component": "System Components",
        "donation_steam_text": "Support via Steam Trade",
        "license": "License",
        "website_neo_organization": "NEO Organization Website",
        "about_program_text": f"Antivirus Crowbar!\nIt will pull any nail out of your PC's coffin!\n(It will at least try, and if it can't, install it) Linux)\nCreated by NEO Organization\nPowered by Department K\nCoded by @AnonimNEO, Total lines of code: {ALL_LINE}\nProgrammers/Conceptualists/Artists/Testers: @AnonimNEO\nLicense: GPL v3.0 Copyleft 🄯 {years_copyleft}\n",
        "ap_exception_text": "An unknown error occurred in the AboutProgram component!",
        "not_stable": "Unavailable due to instability",
        "read_dir_error": "Error reading directory",
        "read_image_error": "Failed to load image",
        # T
        "import_error": "Import error",
        "replacement_is_used": "Replacement is used",
        "component_import_error": "Error importing Component",
        "component": "Component",
        "not_available": "Not available",
        "not_available2": "Not available",
        "library": "Library",
        "critical_fail_detect": "Critical program corruption detected! The program core cannot be started",
        "damage": "Damage",
        "RUN_IN_RECOVERY": "Starting in the Windows Recovery Environment",
        "run_in_normal": "Starting in the standard Windows environment",
        "environment_error": "Error detecting environment",
        "load_bush": "Loading registry hives from disk",
        "unload_bush": "Shutting down, unloading registry hives...",
        "runtime_error": "Critical error initializing program",
        "use_default_font": "Using default font",
        "trey_error": "Tray error",
        "open_with": "Open with",
        "bad_password_for_console": "Invalid captcha entry.\nThe developer console will not launch.",
        "enter_number": "Enter a number",
        "open": "Open",
        "utilities": "Utilities",
        "icon_start_error": "Error starting icon",
        "t_critical_error": "An unknown error occurred in the Tray component",
        "multiprocessing_error": "Critical error during multithreading",
        "restart_program": "Restart the program",
        "admin_error": "Error obtaining administrator rights",
        "checking_damage_error": "Error checking for critical damage",
        "emergency_restart": "Emergency restart",
        "attempt_import_t": "Attempt to start the program as a separate module!",
        "start_cash_error": "Error starting the script engine",
        "enable_debug_mode": "Enable Test Mode",
        "warning_debug_mode_on": "WARNING\nTest mode is enabled!",
        "documentation": "Documentation",
        "fatal_error": "Fatal error",
        "in_start_crowbar": "Unable to start when starting Mount Antivirus. Missing tkinter graphics library, see logs for details.",
        # ARM
        "scheduler_error": "Failed to connect to task scheduler",
        "edit_task_error": "Error changing task state",
        "delete_task_error": "Error deleting task",
        "user_not_found": "User not found",
        "enter_user_name": "Enter the correct username",
        "metadata_error": "Error getting file metadata",
        "startup_error": "Error accessing user startup folder",
        "key_not_found": "Registry key not found",
        "read_key_error": "Error reading registry key",
        "create_key": "Registry parameter created",
        "with_type": "with type",
        "in": "in",
        "permission_error": "Insufficient permissions",
        "create_key_error": "Error creating parameter registry value",
        "update_key": "Registry value changed successfully",
        "update_key_error": "Error changing registry value",
        "delete_key": "Registry value deleted",
        "delete_key_error": "Registry value deleted",
        "file_delete": "File deleted",
        "file_delete_error": "Error deleting file",
        "save_xml_task_error": "Error saving XML task",
        "task_error": "Task processing error",
        "task_dir_error": "Task directory not found",
        "xml_task_error": "Error processing task file",
        "on": "enabled",
        "off": "disabled",
        "task": "Task",
        "success": "successful",
        "from_com": "via COM",
        "from_xml": "via XML",
        "xml_error": "XML error",
        "delete_task_com": "Deleted via COM",
        "xml_task_delete": "Task XML file deleted",
        "xml_task_delete_error": "Error deleting XML file",
        "delete_file?": "Are you sure you want to delete the registry key",
        "enter_new_name_key": "Enter the name of the new registry key",
        "for": "for",
        "arm_help_text": 'The Scheduler tab displays so many tasks because viruses could modify tasks. However, this is extremely rare, so you can disable the display of tasks without the "created by" column. To do this, click View->Show only tasks with a date in the top bar.',
        "arm_critical_error": f"An unknown error occurred in the AutoRunMaster component!",
        "danger": "Threat",
        "suspend_process_for_name": "Freeze processes with the name",
        "kill_process_for_name": "Kill processes with name",
        "action_error": "action error",
        # B
        "browser_called": "browser called with parameters",
        "browser_run_in_recovery": "Downloading pages from the internet is not supported in the recovery environment.\nHowever, offline browsing is available",
        "download_start": "Download started",
        "download_cancel": "Download canceled",
        "download_completed": "Download completed",
        "file_download_on": "File successfully downloaded to",
        "download_fail": "Download error",
        "enter_url_or_file_path": "Enter URL or file path",
        "new_tab": "New tab",
        "html_loaded": "HTML content loaded",
        "file_loaded": "File loaded",
        "page_loaded": "Page loaded",
        # CASH
        "script_deleted": "Script deleted",
        "script_deleted_error": "Error deleting script",
        "execution_completed": "Execution completed",
        "exec_script_error": "Error executing script",
        "script_config": "Script configuration",
        "file_transferred": "File transferred",
        "command_not_found_for_file": "Mount Antivirus doesn't have commands for this file type",
        # Console
        "crowbar_console": "Mount Antivirus Developer Console",
        "crowbar_console_text": "In this console, you manipulate copies of variables, so your actions are unlikely to damage the program. If this happens, restart the console or the program.\n",
        "attempt_command": "attempt to execute command",
        "exit_with_console_text": "No, no. I won't let you bypass the captcha (at least I'll try)",
        # EC
        "open_process_error": "Failed to open process",
        "error_code": "Error code",
        "installed": "installed",
        "removed": "removed",
        "process_critical": "Process criticality",
        "target": "target",
        "edit_critical_error": "Error changing criticality",
        "edit_critical_unknown_error": "Unknown error changing criticality",
        "process": "Process",
        "not_found": "not found",
        "criticality_status": "Process criticality value",
        "changed_to": "changed to",
        "no_changed": "not changed",
        "ec_critical_error": "An unknown error occurred in the EditCriticality component",
        # OF
        "pac_text": f"The Program Authentication Key (PAK) is a key for confirming that this program is genuine.\nIf you see a key that You specified the key during compilation, which means you're looking at the genuine Antivirus Mount. If the key doesn't match yours, it means you're looking at a clone of the program masquerading as Antivirus Mount.\n\nCheckpoint - {PROGRAM_AUTHENTICATION_CLYTH}",
        "start_thread": "Successfully started thread for",
        "start_process": "Successfully started process for",
        "start_theard_error": "Error starting thread for process",
        "start_process_error": "Error starting process for process",
        "restart_ca": "Restarting the program",
        "system_found": "System found on",
        "unknown_error": "Unknown error",
        "bush_not_found": "Hive file not found",
        "bush": "Hive",
        "success_load": "successfully loaded from",
        "load_bush_error": "Error loading hive",
        "success_unload": "successfully unloaded unloaded",
        "unload_bush_error": "Error unloading bush",
        "get_user_name_error": "Error getting user name",
        "open_file_error": "Failed to open file",
        "with_program": "using the specified program",
        "start_error": "Error starting",
        "start_command_error": "Error executing command",
        "execute": "Execute",
        "enable_debug_mode_text": "Are you sure you want to enable Test Mode?\nThis will result in more accurate logs with potentially sensitive data.\nTest Mode will also unlock test components.",
        "debug_mode_on": "TEST MODE is enabled",
        "decoy_mode_error": "Error creating fake activity",
        "reg_key_delete_error": "Error deleting registry key",
        "reg_key_delete": "Registry key deleted",
        "create_reg_key": "Registry key created",
        "protect_window_on": "Window move protection enabled",
        "protect_window_off": "Window move protection disabled",
        "window_block": "Window blocked for",
        "second": "seconds",
        "excessive_movements": "Excessive movements",
        "for2": "per",
        "milliseconds": "ms",
        "sharp_jump": "Sharp jump",
        "attack": "Attack",
        "start_in_ghost_mode": "Run in ghost mode",
        "start_in_ghost_mode_error": "Error starting in ghost mode",
        "browser_problem": "The built-in browser has problems and is currently not available in the program.\nOpen the documentation link in the default browser?",
        # E
        "dyrachok_test_log_text": "Dyrachok test failed",
        "dyrachok_test_text": "You are viewing TikTok!\nThe program will not close.",
        "watch_tiktok?": "Are you watching TikTok?",
        "exit_error": "Error exiting",
        "exit_program": "Exiting program...",
        "bad_capcha": "Invalid captcha input.\nThe program will not close.",
        "enter_result_example": "Enter the result of this example",
        "bad_result_example": "Invalid example input",
        "bad_enter_number": "Invalid number input",
        "want_exit?": "Are you sure you want to exit this software?",
        "attempting_to_exit": "Attempting to exit the program",
        "cancel_exit": "Cancel exit",
        "e_critical_error": "An unknown error occurred in the Exit component!",
        # GFA
        "not_dir": "Path does not exist",
        "full_access_set": "Full access rights set",
        "error": "Error",
        "file_error": "Error working with file",
        "to_access": "to access",
        "get_sid_error": "Error getting user SID",
        "get_description_error": "Error getting security descriptor",
        "ace_error": "Error adding ACE",
        "set_access_error": "Error setting rights",
        "success_set_full_access": "Full access rights to registry set",
        "regedit_error": "Error working with registry",
        # R
        "attempt_to_reboot": "Attempting reboot via",
        "r_critical_error": "An unknown error occurred in the Restart Component method",
        "next_method": "Proceeding to the next method",
        "all_method_used": "All possible reboot methods have been tried Windows, none were successful.",
        # SP
        "simulation": "Simulation",
        "removal": "Removing",
        "create_dir": "Directory created",
        "create_dir_error": "Error creating directory",
        "create_file": "File created",
        "create_file_error": "Error creating file",
        "delete_dir": "Directory deleted",
        "delete_dir_error": "Error deleting directory",
        "start_simulation": "Starting simulation for",
        "simulation_for": "Simulation for",
        "completed": "completed",
        "simulation_completed": "Simulation completed.",
        "sp_confirmation": "Are you sure you want to remove all phantom items? This may corrupt the actual installed items.",
        "delete_simulation": "Deleting simulation for",
        "delete_simulation_for": "Deleting simulation for",
        "delete_completed": "Deletion complete.",
        "sp_critical_error": f"An unknown error occurred in the ScarecrowProtection component!",
        # UA
        "start_recovery_font": "Starting font restoration",
        "font_dir_not_found": "Font directory not found",
        "font": "Font",
        "restored": "restored",
        "correct_font": "already correctly written to the registry",
        "add_in_registry": "added to the registry",
        "font_error": "Error processing font",
        "delete_orphan_font": "Orphan font parameter removed",
        "delete_orphan_font_error": "Error deleting orphan parameter",
        "recovery_font_complete": "Font restoration complete. Found",
        "removed_orphans": "removed orphans",
        "recovery_font_error": "Error recovering fonts",
        "parameter": "Parameter",
        "successfully_reset_to": "successfully reset to",
        "unsupported_type_for": "Unsupported type for",
        "not_found_pass": "not found, skip",
        "reset_error": "Error resetting",
        "block_detect": "Locks detected in",
        "delete_block": "Locks removed",
        "component_work_complete": "Component work completed",
        "ua_critical_error": "An unknown error occurred in the UnlockAll component:",
        "au_result": "The Unlock All component has completed its work results",
        "unlock": "Unlocked ✅",
        "unlock_error": "Unlock error ❌",
        "blocks": "Locks",
        "mouse": "mouse",
        "explorer": "Explorer",
        "user": "user",
        "systems": "systems",
        "fonts": "fonts",
        "check_fonts": "Checking font integrity",
        "all_fonts=": "All font parameters have the same value",
        "not_ttf_or_otf": "Parameter values do not contain .ttf or .otf files",
        "font_problem_detect": "Problems with fonts detected, starting repair",
        "restore_fonts_check_success": "Font integrity check completed successfully, repair is not required",
        "check_fonts_error": "Unknown error while checking fonts",
        "legal_notice": "Message before login",
        # UM
        "net_error": "The net command failed",
        "system_command_error": "System error while executing command",
        "user_name": "User name",
        "create_user": "Create user",
        "delete_users": "Delete selected",
        "change_password": "Change password",
        "get_user_list_error": "Error loading user list",
        "password": "Password",
        "enter_all_data": "Fill in all fields.",
        "success_create": "successfully created",
        "create_user_error": "Error creating user",
        "select_user": "Select a user.",
        "cant_delete_self": "Cannot delete yourself",
        "what_did_you": "I did what I wanted",
        "deleted": "deleted",
        "delete_user_error": "Error deleting user",
        "enter_new_password": "Enter new password:",
        "not_empty": "cannot be empty.",
        "reset": "Reset",
        "reset2": "reset",
        "password_for_user": "Password for user",
        "change_password_error": "Error resetting password for",
        "um_critical_error": "An unknown error occurred in the UsersManager component!",
        # CC
        "start_clean": "Starting Cleanup",
        "from": "from",
        "delete_files_error": "Error deleting the following files",
        "delete_files_success": "Successfully deleted files",
        "cc_log_dir": "A log file was created at the path",
        "cc_critical_error": "An unknown error occurred in the ClearCache component!",
        # CM
        "components": "Components",
        "protect": "Protection",
        "control": "Control",
        "cm_critical_error": "An unknown error occurred in the CrowbarMenu component!",
        # Theme
        "dark": "Dark",
        "white": "Light",
        "red": "Red",
        "blue": "Blue",
        "green": "Green",
        "contrast": "Contrast",
        "gray": "Gray",
        "orange": "Orange",
        "themes": "Themes",
        "topmost": "Always on top",
        "on2": "on",
        "off2": "off",
        "help": "Help",
        "view": "View",
        "show_date": "Show only tasks with a date",
        # FE
        "file": "File",
        "save": "Save",
        "save_as": "Save As",
        "exit": "Exit",
        "editing": "Editing",
        "cancel": "Cancel",
        "repeat": "Repeat",
        "cut": "Cut",
        "copy": "Copy",
        "paste": "Paste",
        "select_all": "Select all",
        "font_size": "Font size",
        "new_file": "New file",
        "text_file": "Text files",
        "all_files": "All files",
        "file_not_found": "File not found",
        "success_saved": "successfully saved",
        "save_changes?": "You have unsaved changes. Save file before exiting?",
        "match_case": "Match case",
        "whole_words": "Whole Words",
        "back": "Previous",
        "next": "Next",
        "fe_critical_error": "An unknown error occurred in the FileEditor component!",
        "cuttlefish": "Sepia",
        "crowbar_scripts": "Mount Antivirus Scripts",
        "load_file": "while loading a file",
        "save_file": "while saving a file",
        # FR
        "created": "Created",
        "replaced": "replaced",
        "on_disc": "on disk",
        "replace_file_not_found": "Failed to replace file",
        "select_file": "First select or specify a file path!",
        "backup": "Backup",
        "on_dir": "on path",
        "restore": "Restore",
        "from_backup": "from backup",
        "restore_from_backup": "Restored from backup",
        "when_restoring_a_file": "when restoring a file",
        "your_way": "Your way path",
        "sticky_keys": "Sticky keys",
        "specialist_possibilities": "Specialist capabilities",
        "task_manager": "Task Manager",
        "explorer": "Explorer",
        "what_to_replace": "What to replace with",
        "review": "Review",
        "what_are_replace": "What to replace",
        "select_preset": "Select a preset...",
        "replace": "Replace",
        # FM
        "skip_file": "Skipped file",
        "copy_path": "Copy path",
        "search": "Search",
        "loading": "Loading",
        "enter_path": "Enter path",
        "available_disks": "Available disks",
        "path": "Path",
        "delete": "Delete",
        "elements": "elements",
        "you_want_to_delete": "Are you sure you want to delete",
        "delete_error": "Error deleting",
        "elements_copy": "Items copied",
        "clipboard_is_empty": "Clipboard is empty",
        "paste_error": "Paste error",
        "access_check_error_for": "Access check error for",
        "properties": "Properties",
        "meaning": "Value",
        "name": "Name",
        "location": "Location",
        "size": "Size",
        "changed": "Changed",
        "opened": "Opened",
        "file_version": "File version",
        "author": "Author",
        "access_for": "Access permissions for",
        "full_access": "Full access",
        "reading": "Read",
        "record": "Write",
        "launch": "Launching",
        "collecting_properties_error": "Error collecting properties for",
        "read_file_properties_error": "Failed to read file properties",
        "invalid_characters": "contains invalid characters characters",
        "current": "Current",
        "dir": "Directory",
        "new_name_for": "New name for",
        "already_exists": "already exists",
        "name_file_or_dir": "File or directory with the name",
        "renamed": "Renamed",
        "when_renaming": "When renaming",
        "enter_data_file": "Enter content for the file",
        "restore_focus_error": "Failed to restore focus to",
        "up": "Up",
        "rename": "Rename",
        "get_full_access": "Get full access",
        "edit_file": "Edit file",
        "create": "Create",
        "update": "Update",
        "not_dir_selected": "No directory selected for insertion",
        "source_file_not_found": "Source not found (may have been moved)",
        "dont_copy_in_in": "Cannot copy or move an item to the same directory",
        "replace_it": "Replace it?",
        "copied2": "Copied",
        "fm_help_text": "Welcome to File Manager!\nThis component supports:\n1)Full keyboard control\n2)Search - to access it, click the item in the upper left part of the window.",
        "text_for_search": "Search text:",
        "in_current_dir": "In the current directory",
        "cancel2": "Cancel",
        "enter_text_for_search": "Enter search text:",
        "not_current_tab_for_search": "No active tab for searching.",
        "files_containing": "Files containing",
        "not_founded": "not found",
        "info_dir_error": "Error getting directory information",
        "info_file_error": "Error getting file information",
        "search_result": "Search results",
        "fm_exit": "Are you sure you want to exit?",
        "fm_critical_error": "An unknown error occurred in FileManager!",
        "fm_search_text": "The search has started. Results will begin loading into the table now. However, sorting functions will not work at this time.\nWhen the search is complete, the entire table will be sorted automatically.\nYou can also continue working in another tab.",
        "search_error": "Error during search",
        "search_completed": "Search completed",
        "read_file_error": "Error reading file",
        # PM
        "info_process_error": "Error getting process information",
        "ok": "OK",
        "at": "at",
        "kill_processes": "Kill processes",
        "suspend": "Freeze",
        "resume": "Unfreeze",
        "make_it_critical": "Make it critical",
        "remove_criticality": "Remove criticality",
        "to_file": "to file",
        "pm_help_text": "Welcome to the Process Manager! It supports: 1) Selecting and managing multiple processes. 2) Search - to open it, click the item in the upper left part of the window. 3) Frozen processes are marked in gray, and critical ones are marked in red. There are also tabs for easy navigation. \n\nPlease note that Windows creates its own four critical svhost.exe processes, but a virus can change these values, so be careful!",
        "cancel_search": "Stop search",
        "actions": "Actions",
        "pm_critical_error": "An unknown error occurred in the ProcessManager component!",
        "kill_delete_file_process": "Kill + delete the process file",
        "process_dont_close": "Did not close within 3 seconds",
        # Run
        "standard": "Accessories",
        "regedit": "Regedit",
        "taskmgr": "Task Manager",
        "notepad": "Notepad",
        "explorer": "Explorer",
        "cmd": "Command Prompt",
        "powershell": "PowerShell",
        "commands": "Commands",
        "cancel_reboot": "Cancel reboot/shutdown",
        "reboot_pc": "Restart PC",
        "shutdown_pc": "Shutdown PC",
        "end_session": "End session",
        "mode": "Mode:",
        "professional": "professional",
        "simplified": "simplified",
        "file2": "file",
        # SAU
        "compilations": "Compilations",
        "command_end_with_code": "Command ended with code",
        "t_compilation_is_finish": "Trey Component compilation complete!",
        "setting_saved_in": "Settings successfully saved to",
        "settings_save_error": "Error saving settings",
        "settings_backup_created_ob_path": "Backup of settings created at path",
        "settings_export_success": "Export successful, saved to",
        "settings_backup_created_error": "Error creating backup",
        "settings_export_error": "Error exporting settings",
        "archive": "Archive",
        "not_compilation": "Recompilation not possible",
        "bad_archive": "Invalid archive format or corrupted archive",
        "success_unpacked": "unpacked successfully",
        "unpacked_archive_error": "Error unpacking archive",
        "moved": "moved",
        "content": "Contents",
        "moved_error": "Error moving files",
        "enter_path_to_image": "Enter the directory where to move the images.\nDo not enter anything if the images are already in the desired directory (for example, you are simply updating the program)",
        "for_copy_image": "images to a directory",
        "for_copy": "for copying",
        "copy_error": "Error copying",
        "copy_file_error": "images.\nYou may have entered incorrect information. You can move the files yourself. They are in the program directory.",
        "enter_exe_name": "Enter the directory where to move the executable file.\nAlong with the file name, it must include the .exe extension!",
        "copy_exe_error": "You may have entered incorrect information. You can move the files yourself. They are in the program directory.",
        "create_lnk_success": "Shortcut successfully created on the desktop",
        "create_lnk_error": "Errors creating shortcut",
        "successfully_changed_to": "successfully changed to",
        "add_to_autorun_error": "Error adding program to startup",
        "add_program_to_autorun": "Add program to startup?",
        "add_program_to_autorun_error": "An error occurred while adding the program to startup",
        "path_must_string": "Path must be a string",
        "number_must_be_1_to": "Number must be between 1 and",
        "enter_number": "Enter a number.",
        "enter_string": "Value must be a string",
        "field_cannot_be_empty": "Field cannot be empty.",
        "use": "Use",
        "must_list": "Must be a list, tuple, set, or dictionary",
        "syntaxis_error": "Syntax error",
        "invalid_format": "Invalid format",
        "must_be_dictionary": "Value must be a dictionary",
        "dictionary_must_contain_key": "Dictionary must contain key",
        "read_comments_error": "Error reading comments from",
        "parsing_error": "Parsing error",
        "fix_problem_in_fields": "Fix errors in fields (marked in red)",
        "recompilation_required_continue": "Recompilation required! Continue?",
        "create_backup": "Creating backup...",
        "create_backup_error": "Error creating backup",
        "save_settings": "Saving settings...",
        "save_settings_error": "Error saving settings",
        "unpacking_source_code": "Unpacking source code...",
        "unpacking_source_code_error": "Error unpacking source code",
        "preparing_files": "Preparing files...",
        "preparing_files": "Preparing files...",
        "compilation": "Compiling",
        "during_recompilation": "during recompilation",
        "copying_files": "Copying files...",
        "adding_to_autorun": "Adding to autorun...",
        "completed": "completed",
        "delete_compiling_cache": "Are you sure you want to delete all cache and temporary .py files?",
        "clean_completed_deleted_objects": "Cleaning completed.\nDeleted objects",
        "clean_cache_error": "Error clearing cache",
        "ready": "Ready to run",
        "open_error": "Failed to open",
        "log": "File log",
        "export": "Export",
        "import": "Import",
        "delete_cache": "Delete Cache",
        "apply": "Apply",
        "sau_start_text": "Please note that changing parameters is impossible without recompiling the program!\n\nWe recommendExport settings (thereby backing up the settings) before making changes. Do you want to continue?",
        "icon_not_found": "The program icon was not found. If you want to specify your own, click OK and select an icon in the window that appears. If not, click OK and select Cancel in the window that opens.",
        "enter_program_name": "Enter the desired name of the executable file, WITHOUT the file extension!",
        "enter_log_name": "Enter the name of the log file for the installer. You can enter the full path to this log file or leave it blank if you want to disable logging.",
        "sau_critical_error": f"An unknown error occurred during installation.",
        # GUI
        "custom": "Custom",
        "parameter": "parameter",
        "type": "Type",
        "date": "Date",
        "creation": "created",
        "changes": "Changes",
        "discoveries": "Discoveries",
        "system": "System",
        "bit": "Bit depth",
        "registry": "Registry",
        "scheduler": "Scheduler",
        "state": "State",
        "unknown": "unknown",
        "no": "No",
        "change": "Change",
        "turn_off": "Disable",
        "turn_on": "Enable",
        "no_data": "N/A",
        "yes": "Yes",
        "all_process": "All Processes",
        "process2": "Process",
        "critical": "Criticality",
        "status": "Status",
        "user2": "User",
        "frozen": "Frozen",
        "critical_process": "Critical Processes",
        "suspend_process": "Frozen Processes",
        "things": "items",
        "admin": "Administrator",
        "started": "Started",
        "guest": "Guest",
    },
    "ua": {
        "RLP": "Захист Навантаження",
        "ARM": "Майстер Автозавантаження",
        "B": "Браузер",
        "CASH": "Обробник скриптів",
        "PM": "Менеджер процесів",
        "FM": "Файловий менеджер",
        "UA": "Розблокування всього",
        "FE": "Редактор Файлів",
        "FR": "Заміна файлів, що рідко використовуються",
        "CM": "Головне меню",
        "SP": "Будило від вірусів",
        "CC": "Очищення Кеша",
        "Console": "Консоль розробника",
        "UM": "Менеджер Користувачів",
        "R": "Перезапуск ПК",
        "Run": "Запуск всього",
        "OBPC": "Голосове Управління",
        "encryption": "Шифрування",
        "EC": "Зміна Критичності процесу",
        "GFA": "Отримання повних прав",
        "OF": "Інші Компоненти",
        "RS": "Генератор заголовків",
        "E": "Вихід із програми",
        "AP": "Про Програму",
        "SAU": "Налаштування",
        "RM": "Моніторинг Реєстру",
        "SIM": "Менеджер установки",
        #AP
        "version_component": "Версії Компонентів",
        "pac": "Ключ КПП",
        "general_component": "Головні Компоненти",
        "program_kernel": "Ядро програми (трей)",
        "mini_component": "Міні Компоненти",
        "system_component": "Системні компоненти",
        "donation_steam_text": "Підтримати через трейд у Steam",
        "license": "Ліцензія",
        "website_neo_organization": "Веб-Сайт NEO Organization",
        "about_program_text": f"Антивірус Монтування!\nВитягнете будь-який цвях з кришки труни вашого ПК!\n(як мінімум спробує, а якщо не зміг - постав Linux)\nCreated by NEO Organization\nPowered by Departament K\nCoded by @AnonimNEO, Всього {ALL_LINE}\nПрограммісти/Задумщики/Художники/Тестувальники : @AnonimNEO\nЛіцензія: GPL v3.0 Copyleft 🄯 {years_copyleft}\n",
        "ap_exception_text": "У Компоненті AboutProgram відбулася невідома помилка!",
        "not_stable": "недоступний через нестабільність",
        "read_dir_error": "Помилка читання каталогу",
        "read_image_error": "Не вдалося завантажити зображення",
        # T
        "import_error": "Помилка імпорту",
        "replacement_is_used": "Використовується заміна",
        "component_import_error": "Помилка імпорту Компонента",
        "component": "Компонент",
        "not_available": "не доступний",
        "not_available2": "не доступна",
        "library": "Бібліотека",
        "critical_fail_detect": "Виявлено критичні пошкодження програми! Ядро програми не може бути запущене",
        "damage": "Ушкодження",
        "RUN_IN_RECOVERY": "Запуск у середовищі відновлення Шindows",
        "run_in_normal": "Запуск у стандартному середовищі Шindows",
        "environment_error": "Помилка визначення середовища",
        "load_bush": "Завантаження кущів реєстру з диска",
        "unload_bush": "Завершення роботи, вивантаження кущів реєстру...",
        "runtime_error": "Критична помилка під час ініціалізації програми",
        "use_default_font": "Використовується стандартний шрифт",
        "trey_error": "Помилка трею",
        "open_with": "Відкрити за допомогою",
        "bad_password_for_console": "Неправильне введення капчі.\nКонсоль розробника не буде запущена.",
        "enter_number": "Введіть число",
        "open": "Відкрити",
        "utilities": "Утиліти",
        "icon_start_error": "Помилка запуску іконки",
        "t_critical_error": "У Компоненті Trey сталася невідома помилка",
        "multiprocessing_error": "Критична помилка при багатопоточності",
        "restart_program": "Перезапустити програму",
        "admin_error": "Помилка при отриманні прав адміністратора",
        "checking_damage_error": "помилка під час перевірки критичних ушкоджень",
        "emergency_restart": "Аварійний перезапуск",
        "attempt_import_t": "Спроба запуску програми як окремого модуля!",
        "start_cash_error": "Помилка запуску движка скриптів",
        "enable_debug_mode": "Увімкнути тестовий режим",
        "warning_debug_mode_on": "УВАГА\nУвімкнено тестовий режим!",
        "documentation": "Документація",
        "fatal_error": "Фатальна помилка",
        "in_start_crowbar": "при запуску Антивірусу Монтування, запуск не можливий. Відсутня графічна бібліотека tkinter, докладніше в логах.",
        # ARM
        "scheduler_error": "Не вдалося підключитися до планувальника завдань",
        "edit_task_error": "Помилка зміни стану завдання",
        "delete_task_error": "Помилка видалення завдання",
        "user_not_found": "Не знайдено користувача",
        "enter_user_name": "Введіть потрібне ім'я користувача",
        "metadata_error": "Помилка при отриманні метаданих файлу",
        "startup_error": "Помилка доступу до папки автозавантаження користувача",
        "key_not_found": "Ключ реєстру не знайдено",
        "read_key_error": "Помилка при зчитуванні ключа реєстру",
        "create_key": "Створено параметр реєстру",
        "with_type": "з типом",
        "in": "в",
        "permission_error": "Недостатньо прав",
        "create_key_error": "Помилка при створенні парамитра реєстру",
        "update_key": "Успішно змінено параметр реєстру",
        "update_key_error": "Помилка зміни реєстру",
        "delete_key": "Видалено параметр реєстру",
        "delete_key_error": "Видалено параметр реєстру",
        "file_delete": "Видалений файл",
        "file_delete_error": "Помилка видалення файлу",
        "save_xml_task_error": "Помилка збереження XML завдання",
        "task_error": "Помилка обробки завдання",
        "task_dir_error": "Каталог завдань не знайдено",
        "xml_task_error": "Помилка обробки файлу завдання",
        "on": "включена",
        "off": "відключена",
        "task": "Завдання",
        "success": "успішно",
        "from_com": "через COM",
        "from_xml": "через XML",
        "xml_error": "Помилка XML",
        "delete_task_com": "віддалена через COM",
        "xml_task_delete": "XML файл завдання видалено",
        "xml_task_delete_error": "Помилка видалення XML файлу",
        "delete_file?": "Ви впевнені, що хочете видалити параметр реєстру",
        "enter_new_name_key": "Введіть ім'я нового параметра реєстру",
        "for": "для",
        "arm_help_text": 'У вкладці планувальник відображається так багато завдань, тому що віруси могли модернізувати завдання, але таке вкрай рідко, тому ви можете вимкнути відображення задач без графа "створено". Для цього натисніть пункт у верхній панелі вікна: вид->Показувати тільки завдання з датою.',
        "arm_critical_error": f"У Компоненті AutoRunMaster сталася невідома помилка!",
        "danger": "Загроза",
        "suspend_process_for_name": "Заморозити процеси з ім'ям",
        "kill_process_for_name": "Вбити процеси з ім'ям",
        "action_error": "помилка при дії",
        # B
        "browser_called": "браузер викликаний параметрами",
        "browser_run_in_recovery": "У середовищі відновлення не підтримується завантаження сторінок з інтернету.\nОднак перегляд офлайн сторінок доступний",
        "download_start": "Почато скачування",
        "download_cancel": "Скасовано скачування",
        "download_completed": "Завантаження завершено",
        "file_download_on": "Файл успішно завантажений в",
        "download_fail": "Помилка при скачуванні",
        "enter_url_or_file_path": "Введіть URL або шлях до файлу",
        "new_tab": "Нова вкладка",
        "html_loaded": "Завантажений контент HTML",
        "file_loaded": "Завантажений файл",
        "page_loaded": "Завантажена сторінка",
        # CASH
        "script_deleted": "Скрипт видалено",
        "script_deleted_error": "Помилка видалення скрипта",
        "execution_completed": "Виконання завершено",
        "exec_script_error": "Помилка під час виконання скрипта",
        "script_config": "Конфігурація скрипта",
        "file_transferred": "Передано файл",
        "command_not_found_for_file": "Антивірус Монтування не має команд для цього типу файлу",
        # Console
        "crowbar_console": "Консоль Розробника Антивірусу Монтування",
        "crowbar_console_text": "У цій консолі ви оперуєте копіями змінних так, що ваші дії навряд чи можуть пошкодити програму.\nЯкщо це сталося, перезапустіть консоль або програму.\n",
        "attempt_command": "спроба виконати команду",
        "exit_with_console_text": "Не Я не дам тобі обійти капчу (як мінімум спробую)",
        # EC
        "open_process_error": "Не вдалося відкрити процес",
        "error_code": "Код помилки",
        "installed": "встановлена",
        "removed": "знята",
        "process_critical": "Критичність процесу",
        "target": "цільове",
        "edit_critical_error": "Помилка зміни критичності",
        "edit_critical_unknown_error": "Невідома помилка при зміні критичності",
        "процес": "Процес",
        "not_found": "не знайдено",
        "criticality_status": "Значення критичності процесу",
        "changed_to": "змінено на",
        "no_changed": "не було змінено",
        "ec_critical_error": "У Компоненті EditCriticality сталася невідома помилка",
        #OF
        "pac_text": f"Ключ Справжності Програми (КПП) - це ключ для підтвердження, що ця програма дійсна. {PROGRAM_AUTHENTICATION_CLYTH}",
        "start_thread": "Успішно запущено потік для",
        "start_process": "Успішно запущено процес для",
        "start_theard_error": "Помилка при запуску потоку для процесу",
        "start_process_error": "Помилка при запуску процесу для процесу",
        "restart_ca": "Перезапуск програми",
        "system_found": "Систему знайдено на",
        "unknown_error": "Невідома помилка",
        "bush_not_found": "Файл куща не знайдено",
        "bush": "Кущ",
        "success_load": "успішно завантажений з",
        "load_bush_error": "Помилка при завантаженні куща",
        "success_unload": "успішно вигративже",
        "unload_bush_error": "Помилка при розвантаженні куща",
        "get_user_name_error": "Помилка отримання імені користувача",
        "open_file_error": "Не вдалося відкрити файл",
        "with_program": "за допомогою зазначеної програми",
        "start_error": "Помилка при запуску",
        "start_command_error": "Помилка під час виконання команди",
        "execute": "Виконати",
        "enable_debug_mode_text": "Ви впевнені, що хочете увімкнути тестовий режим?\nЦе призведе до більш точних логів з можливо чутливими даними.\nТакже в тестовому режимі будуть розблоковані тестові компоненти.",
        "debug_mode_on": "Увімкнено ТЕСТОВИЙ РЕЖИМ",
        "decoy_mode_error": "Помилка при створенні фейкової активності",
        "reg_key_delete_error": "Помилка видалення ключа реєстру",
        "reg_key_delete": "Видалено ключ реєстру",
        "create_reg_key": "Створено ключ реєстру",
        "protect_window_on": "Захист від переміщення вікна включений",
        "protect_window_off": "Захист від переміщення вікна вимкнено",
        "window_block": "Вікно заблоковане на",
        "second": "сек",
        "excessive_movements": "Занадто часті рухи",
        "for2": "за",
        "milliseconds": "мс",
        "sharp_jump": "Різкий стрибок",
        "attack": "Атака",
        "start_in_ghost_mode": "Запущено в прихованому режимі",
        "start_in_ghost_mode_error": "Помилка при запуску в прихованому режимі",
        "browser_problem": "Вбудований браузер має проблеми і на даний момент відсутній у програмі.\nВідкрити посилання на документацію в браузері за замовчуванням?",
        # E
        "dyrachok_test_log_text": "Перевірка на дурня не пройшла",
        "dyrachok_test_text": "Ви дивіться тикток!\nПрограма не буде закрита.",
        "watch_tiktok?": "Чи дивитесь ви тикток?",
        "exit_error": "Помилка при виході",
        "exit_program": "Завершення роботи програми...",
        "bad_capcha": "Неправильне введення капчі.\nПрограма не буде закрита.",
        "enter_result_example": "Введіть результат цього прикладу",
        "bad_result_example": "введення прикладу неправильне",
        "bad_enter_number": "Неправильне введення числа",
        "want_exit?": "Ви дійсно хочете вийти з цього програмного забезпечення?",
        "attempting_to_exit": "Спроба виходу з програми",
        "cancel_exit": "Скасування виходу",
        "e_critical_error": "У Компоненті Exit сталася невідома помилка!",
        # GFA
        "not_dir": "Шлях не існує",
        "full_access_set": "Повні права встановлені",
        "error": "Помилка",
        "file_error": "Помилка під час роботи з файлом",
        "to_access": "для доступу до",
        "get_sid_error": "Помилка отримання SID користувача",
        "get_description_error": "Помилка отримання дескриптора безпеки",
        "ace_error": "Помилка додавання ACE",
        "set_access_error": "Помилка встановлення прав",
        "success_set_full_access": "Повні права на реєстр встановлено",
        "regedit_error": "Помилка при роботі з реєстром",
        #R
        "attempt_to_reboot": "Спроба перезавантаження через",
        "r_critical_error": "У Компоненті Restart відбулася невідома помилка в методі",
        "next_method": "Перехід до наступного способу",
        "all_method_used": "Були виконані всі можливі способи перезавантаження шindows, не один не увінчався успіхом.",
        #SP
        "Simulation": "Симуляція",
        "removal": "Видалення",
        "create_dir": "Створено каталог",
        "create_dir_error": "Помилка створення каталогу",
        "create_file": "Створено файл",
        "create_file_error": "Помилка створення файлу",
        "delete_dir": "Видалено каталог",
        "delete_dir_error": "Помилка при видаленні каталогу",
        "start_simulation": "Запуск симуляції для",
        "simulation_for": "Симуляція для",
        "completed": "завершена",
        "simulation_completed": "Симуляція завершена.",
        "sp_confirmation": "Ви впевнені, що хочете видалити всі фантомні елементи?\nЦе може пошкодити ці встановлені.",
        "delete_simulation": "Видалення симуляції для",
        "delete_simulation_for": "Видалення симуляції для",
        "delete_completed": "Видалення завершено.",
        "sp_critical_error": f"У Компоненті ScarecrowProtection сталася невідома помилка!",
        #UA
        "start_recovery_font": "Початок відновлення шрифтів",
        "font_dir_not_found": "Каталог шрифтів не знайдено",
        "font": "Шрифт",
        "відновлено": "відновлено",
        "correct_font": "вже коректно записано в реєстрі",
        "add_in_registry": "доданий до реєстру",
        "font_error": "Помилка при обробці шрифту",
        "delete_orphan_font": "Видалено параметр сирітського шрифту",
        "delete_orphan_font_error": "Помилка при видаленні параметра-сиріт",
        "recovery_font_complete": "Відновлення шрифтів завершено. Знайдено",
        "removed_orphans": "видалено сиріт",
        "recovery_font_error": "Помилка відновлення шрифтів",
        "parameter": "Параметр",
        "successfully_reset_to": "успішно скинуто в",
        "unsupported_type_for": "Непідтримуваний тип для",
        "not_found_pass": "не знайдено, перепустка",
        "reset_error": "Помилка при скиданні",
        "block_detect": "Виявлено блокування в",
        "delete_block": "Видалені блокування",
        "component_work_complete": "Робота компонента завершена",
        "ua_critical_error": "У Компоненті UnlockAll сталася невідома помилка:",
        "au_result": "Компонент розблокування всього завершив роботу результати",
        "unlock": "Розблоковано ✅",
        "unlock_error": "Помилка розблокування❌",
        "blocks": "Блокування",
        "mouse": "миші",
        "explorer": "провідника",
        "user": "користувача",
        "системи": "системи",
        "fonts": "шрифтів",
        "check_fonts": "Перевірка цілісності шрифтів",
        "all_fonts=": "Усі параметри шрифтів мають однакове значення",
        "not_ttf_or_otf": "У значеннях параметрів відсутні файли .ttf або .otf",
        "font_problem_detect": "Виявлено проблеми зі шрифтами, запуск відновлення",
        "restore_fonts_check_success": "Перевірка цілісності шрифтів завершена успішно, відновлення не потрібне",
        "check_fonts_error": "Невідома помилка під час перевірки шрифтів",
        "legal_notice": "Повідомлення перед входом до системи",
        #UM
        "net_error": "Команда net завершилася з помилкою",
        "system_command_error": "Системна помилка під час виконання команди",
        "user_name": "Ім'я користувача",
        "create_user": "Створити користувача",
        "delete_users": "Видалити вибраних",
        "change_password": "Змінити пароль",
        "get_user_list_error": "Помилка завантаження списку користувачів",
        "password": "Пароль",
        "enter_all_data": "Заповніть усі поля.",
        "success_create": "успішно створено",
        "create_user_error": "Помилка при створенні користувача",
        "select_user": "Виберіть користувача.",
        "cant_delete_self": "Не можна видалити себе",
        "what_did_you": "Бач, що захотів",
        "deleted": "віддалений",
        "delete_user_error": "Помилка при видаленні користувача",
        "enter_new_password": "Введіть новий пароль:",
        "not_empty": "не може бути порожнім.",
        "reset": "Скинути",
        "reset2": "скинутий",
        "password_for_user": "Пароль для користувача",
        "change_password_error": "Помилка під час скидання пароля для",
        "um_critical_error": "У Компоненті UsersManager сталася невідома помилка!",
        # CC
        "start_clean": "Запуск очищення",
        "from": "із",
        "delete_files_error": "Помилка видалення наступних файлів",
        "delete_files_success": "Успішно видалені файли",
        "cc_log_dir": "Лог файл був створений на шляху",
        "cc_critical_error": "У Компоненті ClearCache сталася невідома помилка!",
        # CM
        "components": "Компоненти",
        "protect": "Захист",
        "control": "Управління",
        "cm_critical_error": "У Компоненті CrowbarMenu сталася невідома помилка!",
        # Theme
        "Dark": "Темна",
        "white": "Світла",
        "red": "Червона",
        "blue": "Синя",
        "green": "Зелена",
        "contrast": "Контрастна",
        "gray": "Сірий",
        "orange": "Помаранчева",
        "themes": "Теми",
        "topmost": "Поверх усіх вікон",
        "on2": "вкл",
        "off2": "викл",
        "help": "Допомога",
        "view": "Вигляд",
        "show_date": "Показувати лише завдання з датою",
        # FE
        "file": "Файл",
        "save": "Зберегти",
        "save_as": "Зберегти як",
        "exit": "Вихід",
        "editing": "Редагування",
        "cancel": "Скасувати",
        "repeat": "Повторити",
        "cut": "Вирізати",
        "copy": "Копіювати",
        "paste": "Вставити",
        "select_all": "Виділити все",
        "font_size": "Розмір шрифту",
        "new_file": "Новий файл",
        "text_file": "Текстові файли",
        "all_files": "Всі файли",
        "file_not_found": "Файл не знайдено",
        "success_saved": "успішно збережено",
        "save_changes?": "У вас є незбережені зміни. Зберегти файл перед виходом?",
        "match_case": "Враховувати регістр",
        "whole_words": "Слова цілком",
        "back": "Назад",
        "next": "Далі",
        "fe_critical_error": "У Компоненті FileEditor сталася невідома помилка!",
        "cuttlefish": "Сепія",
        "crowbar_scripts": "Скрипти Антивірусу Монтування",
        "load_file": "при завантаженні файлу",
        "save_file": "при збереженні файлу",
        # FR
        "created": "Створено",
        "replaced": "замінено",
        "on_disc": "на диску",
        "replace_file_not_found": "Не вдалося замінити файл",
        "select_file": "Спочатку виберіть або вкажіть шлях до файлу!",
        "backup": "Бекап",
        "on_dir": "по дорозі",
        "restore": "Відновити",
        "from_backup": "з бекапу",
        "restore_from_backup": "Відновлено з бекапу",
        "when_restoring_a_file": "при відновленні файлу",
        "your_way": "Свій шлях",
        "sticky_keys": "Залипання клавіш",
        "specialist_possibilities": "Спец. можливості",
        "task_manager": "Диспетчер завдань",
        "explorer": "Провідник",
        "what_to_replace": "На що замінити",
        "review": "Огляд",
        "what_are_replace": "Що замінюємо",
        "select_preset": "Виберіть пресет...",
        "replace": "Замінити",
        # FM
        "skip_file": "Пропущений файл",
        "copy_path": "Скопіювати шлях",
        "search": "Пошук",
        "loading": "Завантаження",
        "enter_path": "Введіть шлях",
        "available_disks": "Доступні диски",
        "path": "Шлях",
        "delete": "Видалити",
        "elements": "елементів",
        "you_want_to_delete": "Ви впевнені, що хочете видалити",
        "delete_error": "Помилка при видаленні",
        "elements_copy": "Скопійовано елементів",
        "clipboard_is_empty": "Буфер обміну порожній",
        "paste_error": "Помилка вставки",
        "access_check_error_for": "Помилка перевірки доступу для",
        "properties": "Властивості",
        "meaning": "Значення",
        "name": "Ім'я",
        "location": "Розташування",
        "size": "Розмір",
        "changed": "Змінено",
        "opened": "Відкритий",
        "file_version": "Версія файлу",
        "author": "Автор",
        "access_for": "Права доступу (для",
        "full_access": "Повний доступ",
        "reading": "Читання",
        "record": "Запис",
        "launch": "Запуск",
        "collecting_properties_error": "Помилка при збиранні властивостей для",
        "read_file_properties_error": "Не вдалося прочитати властивості файлу",
        "invalid_characters": "містить неприпустимі символи",
        "current": "Поточний",
        "dir": "Каталог",
        "new_name_for": "Нове ім'я для",
        "already_exists": "вже існує",
        "name_file_or_dir": "Файл або каталог з ім'ям",
        "renamed": "Перейменовано",
        "when_renaming": "при перейменуванні",
        "enter_data_file": "Введіть вміст для файлу",
        "restore_focus_error": "Не вдалося відновити фокус на",
        "up": "Вгору",
        "rename": "Перейменувати",
        "get_full_access": "Отримати повні права",
        "edit_file": "Відредагувати файл",
        "create": "Створити",
        "update": "Оновити",
        "not_dir_selected": "Не вибрано каталог для вставки",
        "source_file_not_found": "Джерело не знайдено (можливо, було переміщено)",
        "dont_copy_in_in": "Не можна скопіювати або перемістити елемент до того ж каталогу",
        "replace_it": "Замінити його?",
        "copied2": "Скопійовано",
        "fm_help_text": "Ласкаво просимо у Файловий Менеджер!\nЦей компонент підтримує:\n1)Повне керування з клавіатури\n2)Пошук - щоб його викликати натисніть на пункт у верхній лівій частині вікна.",
        "text_for_search": "Текст для пошуку:",
        "in_current_dir": "У поточному каталозі",
        "cancel2": "Скасування",
        "enter_text_for_search": "Введіть текст для пошуку:",
        "not_current_tab_for_search": "Немає активної вкладки для пошуку.",
        "files_containing": "Файли, що містять",
        "not_founded": "не знайдені",
        "info_dir_error": "Помилка отримання інформації про каталог",
        "info_file_error": "Помилка отримання інформації про файл",
        "search_result": "Результати пошуку",
        "fm_exit": "Ви впевнені, що хочете вийти?",
        "fm_critical_error": "У FileManager сталася невідома помилка!",
        "fm_search_text": "Пошук почався, результати почнуть підвантажуватися в таблицю вже зараз, проте функції сортування зараз не будуть працювати.",
        "search_error": "Помилка під час пошуку",
        "search_completed": "Пошук завершено",
        "read_file_error": "Помилка при читанні файлу",
        # PM
        "info_process_error": "Помилка при отриманні інформації про процес",
        "ok": "ОК",
        "at": "при",
        "kill_processes": "Вбити процеси",
        "suspend": "Заморозити",
        "resume": "Розморозити",
        "make_it_critical": "Зробити критичними",
        "remove_criticality": "Зняти критичність",
        "to_file": "до файлу",
        "pm_help_text": "Ласкаво просимо до Менеджер Процесів, він підтримує:\n1)Виділення декількох процесів і роботу з ними\n2)Пошук - щоб його викликати натисніть на пункт вгорі лівої частини вікна.\n3)Заморожені процеси - помічені сірим кольором, а критичні - червоні - червоні. навігації.\n\nВрахуйте, що windows створює свої 4 критичних процесів svhost.exe, але вірус може змінити ці значення, будьте пильні!",
        "cancel_search": "Припинити пошук",
        "діяння": "Дії",
        "pm_critical_error": "У Компоненті ProcessManager сталася невідома помилка!",
        "kill_delete_file_process": "Вбити + видалити файл процесу",
        "process_dont_close": "не закрився за 3 секунди",
        # Run
        "standard": "Стандартні",
        "regedit": "редактор реєстру",
        "taskmgr": "диспетчер завдань",
        "notepad": "блокнот",
        "explorer": "провідник",
        "cmd": "командний рядок",
        "PowerShell": "PowerShell",
        "commands": "Команди",
        "cancel_reboot": "Скасувати перезавантаження/вимкнення",
        "reboot_pc": "Перезавантажити ПК",
        "shutdown_pc": "Вимкнути ПК",
        "end_session": "завершити сеанс",
        "mode": "Режим:",
        "professional": "професійний",
        "simplified": "спрощений",
        "file2": "файла",
        # SAU
        "compilations": "Компіляції",
        "command_end_with_code": "Команда завершилася з кодом",
        "t_compilation_is_finish": "Компіляцію Компоненту Trey завершено!",
        "setting_saved_in": "Налаштування успішно збережено в",
        "settings_save_error": "Помилка збереження налаштувань",
        "settings_backup_created_ob_path": "Резервна копія налаштувань створена шляхом",
        "settings_export_success": "Експорт пройшов успішно, збережено в",
        "settings_backup_created_error": "Помилка створення резервної копії",
        "settings_export_error": "Помилка експорту налаштувань",
        "archive": "Архів",
        "not_compilation": "Перекомпіляція неможлива",
        "bad_archive": "Неправильний формат архіву або пошкоджений архів",
        "success_unpacked": "успішно розпакований",
        "unpacked_archive_error": "Помилка при розпакуванні архіву",
        "moved": "переміщено",
        "content": "Вміст",
        "moved_error": "Помилка під час переміщення файлів",
        "enter_path_to_image": "Введіть каталог куди перемістити зображення\nНічого не вводіть якщо зображення вже в потрібному каталозі\n(наприклад, ви просто оновлюєте програму)",
        "for_copy_image": "зображень у каталог",
        "for_copy": "для копіювання",
        "copy_error": "Помилка копіювання",
        "copy_file_error": "зображень\nМожливо ви ввели неправильні дані, ви можете самі перемістити файли вони знаходяться в каталозі з програмою.",
        "enter_exe_name": "Введіть каталог куди перемістити файл, що виконується\nразом з ім'ям файлу, обов'язково з розширенням .exe!",
        "copy_exe_error": "Можливо ви ввели неправильні дані, ви можете самі перемістити файли, вони знаходяться в каталозі з програмою",
        "create_lnk_success": "Ярлик успішно створений на робочому столі",
        "create_lnk_error": "Помилки при створенні ярлика",
        "successfully_changed_to": "успішно змінено на",
        "add_to_autorun_error": "Помилка при додаванні програми до автозавантаження",
        "add_program_to_autorun": "Додати програму до автозавантаження?",
        "add_program_to_autorun_error": "Відбулася помилка під час додавання програми до автозавантаження",
        "path_must_string": "Шлях має бути рядком",
        "number_must_be_1_to": "Число повинно бути від 1 до",
        "enter_number": "Введіть число.",
        "enter_string": "Значення має бути рядком",
        "field_cannot_be_empty": "Поле не може бути порожнім.",
        "use": "Використовуйте",
        "must_list": "Має бути список, кортеж, безліч або словник",
        "syntaxis_error": "Помилка синтаксису",
        "invalid_format": "Некоректний формат",
        "must_be_dictionary": "Значення має бути словником",
        "dictionary_must_contain_key": "Словник повинен містити ключ",
        "read_comments_error": "Помилка при читанні коментарів з",
        "parsing_error": "Помилка парсингу",
        "fix_problem_in_fields": "Виправте помилки в полях (позначені червоним)",
        "recompilation_required_continue": "Потрібна перекомпіляція!\nПродовжити?",
        "create_backup": "Створення резервної копії...",
        "create_backup_error": "Помилка при створенні бекапу",
        "save_settings": "Збереження налаштувань...",
        "save_settings_error": "Помилка збереження налаштувань",
        "unpacking_source_code": "Розпакування вихідних джерел...",
        "unpacking_source_code_error": "Помилка під час розпакування вихідних джерел",
        "preparing_files": "Підготовка файлів...",
        "preparing_files": "Підготовка файлів...",
        "compilation": "Компіляція",
        "during_recompilation": "при перекомпіляції",
        "copying_files": "Копіювання файлів...",
        "adding_to_autorun": "Додавання в автозавантаження...",
        "completed": "завершено",
        "delete_compiling_cache": "Ви впевнені, що хочете видалити весь кеш і тимчасові .py файли?",
        "clean_completed_deleted_objects": "Очищення завершено.\nВидалено об'єктів",
        "clean_cache_error": "Помилка при очищенні кешу",
        "ready": "Готовий до роботи",
        "open_error": "Не вдалося відкрити",
        "log": "лог файлу",
        "export": "Експорт",
        "import": "Імпорт",
        "delete_cache": "Видалити Кеш",
        "apply": "Застосувати",
        "sau_start_text": "Врахуйте, що зміна параметрів неможлива без перекомпіляції програми!\n\nРекомендуємо зробитиекспорт налаштувань (тим самим зробити резервну копію налаштувань), перед змінами\n\nВи хочете продовжити?",
        "icon_not_found": "Не знайдена іконка програми, якщо хочете вказати власну Натисніть ОК і у вікні виберіть іконку, якщо ні то натисніть ОК і у вікні виберіть Скасувати",
        "enter_program_name": "Введіть бажану назву файлу, що виконується,\nБЕЗ розширення файлу!",
        "enter_log_name": "Введіть назву лог файлу для інсталятора\nМожна ввести повний шлях для цього лог файлу\nабо нічого не вводити, якщо хочете вимкнути логування",
        "sau_critical_error": f"Під час встановлення сталася невідома помилка",
        # GUI
        "custom": "Користувацька",
        "parameter": "параметра",
        "type": "Тип",
        "date": "Дата",
        "creation": "створення",
        "changes": "Зміни",
        "discoveries": "Відкриття",
        "system": "Системна",
        "bit": "Бітність",
        "registry": "Реєстр",
        "scheduler": "Планувальник",
        "state": "Стан",
        "unknown": "невідомо",
        "no": "Ні",
        "change": "Змінити",
        "turn_off": "Вимкнути",
        "turn_on": "Увімкнути",
        "no_data": "Н/Д",
        "yes": "Так",
        "all_process": "Всі процеси",
        "process2": "Процеса",
        "critical": "Критичність",
        "status": "Статус",
        "user2": "Користувач",
        "frozen": "Заморожений",
        "critical_process": "Критичні процеси",
        "suspend_process": "Заморожені процеси",
        "things": "шт",
        "admin": "Адміністратор",
        "started": "Запущено",
        "guest": "Гість", 
    },
}

# Возвращаем нужный текст или сам ключ если нужного текста нет в текущем языке
def l(key, language=CURRENT_LOCALIZATION):
    """
    Функция для получения текста из локализации
    key - имя ключа текста/реплики/диалога
    language - Язык на котором вернуть текст
    return - функция возвращает текст из локализации, если такого ключа в указанной локализации нет то будет возвращён сам ключ
    """
    return localizations.get(language, {}).get(key) or key
